spring:
  application:
    name: greeting-microservice

management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
    
greeting-microservice: 
 greeting: "Pronto"
 default-value: "Mondo"
